#!/bin/tcsh

#$ -N gene_expression
#$ -m bea
#$ -M vcassen@systemsbiology.net
#$ -o /proj/hoodlab/share/vcassen/rna-seq/rnaseq/t/fixtures/readsets/paired2/gene_expression.out
#$ -e /proj/hoodlab/share/vcassen/rna-seq/rnaseq/t/fixtures/readsets/paired2/gene_expression.err
#$ -l h_rt=72:00:00
#$ -P solexatrans


####################################

setenv SGE_ROOT /sge

set ARCH = `$SGE_ROOT/util/arch`
set DEFAULTMANPATH = `$SGE_ROOT/util/arch -m`
set MANTYPE = `$SGE_ROOT/util/arch -mt`

setenv SGE_CELL aegir
setenv SGE_CLUSTER_NAME aegir
unsetenv SGE_QMASTER_PORT
unsetenv SGE_EXECD_PORT


set path = ( $SGE_ROOT/bin/$ARCH $path )
switch ($ARCH)
case "sol*":
case "lx*":
case "hp11-64":
   breaksw
case "*":
   set shlib_path_name = `$SGE_ROOT/util/arch -lib`
   if ( `eval echo '$?'$shlib_path_name` ) then
      set old_value = `eval echo '$'$shlib_path_name`
      setenv $shlib_path_name "$SGE_ROOT/lib/$ARCH":"$old_value"
   else
      setenv $shlib_path_name $SGE_ROOT/lib/$ARCH
   endif
   unset shlib_path_name  old_value
endsw
unset ARCH DEFAULTMANPATH MANTYPE


####################################


time /bin/sh /proj/hoodlab/share/vcassen/rna-seq/rnaseq/t/fixtures/readsets/paired2/gene_expression.s_1.sh


